web/router.ex
defmodule HelloPhoenix.Router do
  use HelloPhoenix.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

#  pipeline :browser_no_csrf do
#    plug :accepts, ["html"]
#    plug :fetch_session
#    plug :fetch_flash
#    plug :put_secure_browser_headers
#  end

  pipeline :session do
    plug HelloPhoenix.Plugs.Session
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/users", HelloPhoenix, as: :user do
    pipe_through [:browser, :session]

    get "/password/reset", UserController, :edit
    put  "/password/reset", UserController, :update

    get "/", SessionController, :home
    get "/home", SessionController, :home

    get "/settings/profile", User.ProfileController, :show
    get "/upload_avatar", User.UploadController, :new_avatar
    post "/upload_avatar", User.UploadController, :update_avatar
    resources "/categorys", User.CategoryController
    resources "/articles", User.ArticleController
    resources "/comments", User.CommentController
    resources "/tags", User.TagController
    resources "/links", User.LinkController
  end

  scope "/", HelloPhoenix do
    pipe_through :browser # Use the default browser stack

    get "/achieve", AchieveController, :index
    get "/projects", ProjectController, :index
    get "/search", SearchController, :index
    get "/about", AboutController, :index

    get "/users/index", SessionController, :index
    get "/users/login", SessionController, :new
    get "/users/logout", SessionController, :delete
    post "/users/login", SessionController, :create
    get "/users/register", UserController, :new
    post "/users/register", UserController, :create
    resources "/tags", TagController, only: [:show]
    resources "/categorys", CategoryController do
        resources "/articles", ArticleController do
            resources "/comments", CommentController, only: [:create]
        end
    end
    get "/", CategoryController, :index
  end

#  scope "/", HelloPhoenix do
#    pipe_through :browser_no_csrf # Use the default browser stack
#  end
# scope "/admin", HelloPhoenix.Admin, as: :admin do
#   pipe_through :browser
#    
#    resources "/reviews", ReviewController
#    resources "/users", UserController
#k  end

  # Other scopes may use custom stacks.
  # scope "/api", HelloPhoenix do
  #   pipe_through :api
  # end
end

web/views/layout_view.ex
defmodule HelloPhoenix.LayoutView do
  use HelloPhoenix.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="Zh_cn" xmlns:v-on="http://www.w3.org/1999/xhtml">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="author" content="firebroo">
        <title>博客 firebroo的个人网站 </title>
        <meta name="keywords" content="firebroo的个人网站,爱上板砖">
        <meta name="description" content=" firebroo的个人网站 - firebroo&#039;s Personal Website">
        <meta property="og:type" content="website">
        <meta property="og:title" content="firebroo的个人网站">
        <meta property="og:site_name" content="firebroo的个人网站">
        <meta property="og:description" content="firebroo的个人网站 - firebroo&#039;s Personal Website">
        <meta name="theme-color" content="#52768e">
        <link href="//cdn.bootcss.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet">
        <link href="<%= static_path(@conn, "/css/app.css") %>" rel="stylesheet"></link>
        <script>
            window.XblogConfig = {"github_username":"firebroo"}
        </script>
    </head>

    <body id="body">
        <style>
            @media  screen and (min-width: 768px) {
            .main-header {
                background-size: 100% auto;
                position: static;
            }
        }
        </style>

        <header class="main-header">
            <div class="container-fluid" style="margin-top: -15px">
                <nav class="navbar site-navbar" role="navigation">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                                                                              data-target="#blog-navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a href="/"
                           class="navbar-brand">firebroo</a>
                    </div>
                    <div class="collapse navbar-collapse fix-top" id="blog-navbar-collapse">
                        <%= if Plug.Conn.get_session(@conn, :user_id) do %> 
                            <ul class="nav navbar-nav navbar-self">
                                <li><a class="menu-item" href="/achieve">归档</a></li>
                                <li><a class="menu-item" href="/projects">项目</a></li>
                                <li><a class="menu-item" href="/about">关于</a></li>
                            </ul>
                            <ul class="nav navbar-nav navbar-right">
                                <li class="dropdown">
                                    <a href="<%= user_session_path(@conn, :home)%>" class="dropdown-toggle" 
                                       data-toggle="dropdown" role="button" 
                                       aria-expanded="false">
                                       <img class="avatar" src="<%= Plug.Conn.get_session(@conn, :user_avatar) %>">
                                       <span class="caret"></span>
                                    </a>
                                    <ul class="dropdown-menu" role="menu">
                                        <li><%= link Plug.Conn.get_session(@conn, :username), to: user_profile_path(@conn, :show) %></li>
                                        <li class="divider"></li>
                                        <li><%= link "主页", to: user_session_path(@conn, :home) %></li>
                                        <li><%= link "管理", to: user_article_path(@conn, :index) %></li>
                                        <li class="divider"></li>
                                        <li><%= link "登出", to: session_path(@conn, :delete) %></li>
                                    </ul>
                                </li>
                            </ul>
                        <% else %>
                            <ul class="nav navbar-nav navbar-self">
                                <li><a class="menu-item" href="/achieve">归档</a></li>
                                <li><a class="menu-item" href="/projects">项目</a></li>
                                <li><a class="menu-item" href="/about">关于</a></li>
                            </ul>
                            <ul class="nav navbar-nav navbar-right blog-navbar navbar-self">
                                <li><%= link "登录", to: session_path(@conn, :new) %></a></li>
                            </ul>
                            <form class="navbar-form navbar-right" role="search" method="get" action="/search">
                                <input type="text" class="form-control" name="q" placeholder="搜索" required>
                            </form>
                        <% end %>
                    </div>
                </nav>
            </div>
            <div class="container-fluid">
                <div class="description">Stay Hungry.Stay Foolish.</div>
            </div>
        </header>

        <div class="container">
            <div class="row">
                <div class="col-md-12">
                <%= if flash = get_flash(@conn, :info) do %>
                    <div class="alert alert-success">
                        <a class="close" data-dismiss="alert" href="#"><i class="fa fa-close"></i></a>
                    <%= flash %>
                    </div>
                <%= end %>
                <%= if flash = get_flash(@conn, :error) do %>
                    <div class="alert alert-danger">
                        <a class="close" data-dismiss="alert" href="#"><i class="fa fa-close"></i></a>
                    <%= flash %>
                    </div>
                <%= end %>
                </div>
            </div>
        </div>

        <%= render @view_module, @view_template, assigns %>
        <footer class="footer" id="footer">
            <div class="copyright">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-12">
                            <span>Copyright © <a href="https://www.firebroo.com">firebroo的个人网站</a></span> |
                            <span><a href="https://github.com/firebroo/phoenix_blog"><i class="fa fa-github fa-fw"></i></a> </span>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
        <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
    </body>
</html>