web/router.ex
defmodule HelloPhoenix.Router do
  use HelloPhoenix.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

#  pipeline :browser_no_csrf do
#    plug :accepts, ["html"]
#    plug :fetch_session
#    plug :fetch_flash
#    plug :put_secure_browser_headers
#  end

  pipeline :session do
    plug HelloPhoenix.Plugs.Session
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/users", HelloPhoenix, as: :user do
    pipe_through [:browser, :session]

    get "/password/reset", UserController, :edit
    put  "/password/reset", UserController, :update

    get "/", SessionController, :home
    get "/home", SessionController, :home

    get "/settings/profile", User.ProfileController, :show
    get "/upload_avatar", User.UploadController, :new_avatar
    post "/upload_avatar", User.UploadController, :update_avatar
    resources "/categorys", User.CategoryController
    resources "/articles", User.ArticleController
    resources "/comments", User.CommentController
    resources "/tags", User.TagController
    resources "/links", User.LinkController
  end

  scope "/", HelloPhoenix do
    pipe_through :browser # Use the default browser stack

    get "/achieve", AchieveController, :index
    get "/projects", ProjectController, :index
    get "/search", SearchController, :index
    get "/about", AboutController, :index

    get "/users/index", SessionController, :index
    get "/users/login", SessionController, :new
    get "/users/logout", SessionController, :delete
    post "/users/login", SessionController, :create
    get "/users/register", UserController, :new
    post "/users/register", UserController, :create
    resources "/tags", TagController, only: [:show]
    resources "/categorys", CategoryController do
        resources "/articles", ArticleController do
            resources "/comments", CommentController, only: [:create]
        end
    end
    get "/", CategoryController, :index
  end

#  scope "/", HelloPhoenix do
#    pipe_through :browser_no_csrf # Use the default browser stack
#  end
# scope "/admin", HelloPhoenix.Admin, as: :admin do
#   pipe_through :browser
#    
#    resources "/reviews", ReviewController
#    resources "/users", UserController
#k  end

  # Other scopes may use custom stacks.
  # scope "/api", HelloPhoenix do
  #   pipe_through :api
  # end
end

web/models/article.ex
defmodule HelloPhoenix.Article do
  use HelloPhoenix.Web, :model

  schema "articles" do
    field :title, :string
    field :body, :string
    field :reading, :integer, default: 0
    field :hash_id, :string
    field :block, :boolean, default: false
    belongs_to :category, HelloPhoenix.Category, foreign_key: :category_id

    has_many :comments, HelloPhoenix.Comment, on_delete: :delete_all
    many_to_many :tags, HelloPhoenix.Tag, join_through: "posts_tags", on_delete: :delete_all

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:title, :body, :reading, :category_id, :block])
    |> validate_required([:title, :body, :category_id])
    #|> strip_unsafe_body(params)
    |> validate_length(:title, min: 5)
    |> unique_constraint(:title)
  end

  @doc """
  添加hash之后的id
  """
  def put_id_hash(%Ecto.Changeset{valid?: false} = changeset, _field1, _filed2) do
     changeset
  end

  def put_id_hash(%Ecto.Changeset{valid?: true} = changeset, field1, filed2) do
    value = get_field(changeset, field1) <> get_field(changeset, filed2)
    changeset |> put_change(:hash_id, :crypto.hash(:sha256, value) |> Base.encode16 |> String.downcase)
  end

  def create_changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:title, :body, :reading, :category_id, :block])
    |> validate_required([:title, :body, :category_id])
    #|> strip_unsafe_body(params)
    |> validate_length(:title, min: 5)
    |> unique_constraint(:title)
    |> put_id_hash(:title, :body)
  end

  defp strip_unsafe_body(model, %{"body" => nil}) do
    model
  end
    
  defp strip_unsafe_body(model, %{"body" => body}) do
    {:safe, clean_body} = Phoenix.HTML.html_escape(body)
    model |> put_change(:body, clean_body)
  end
    
  defp strip_unsafe_body(model, _) do
    model
  end
end

web/controllers/article_controller.ex
defmodule HelloPhoenix.ArticleController do
    use HelloPhoenix.Web, :controller

    # 导入Model
    alias HelloPhoenix.{Article, Comment}

    def show(conn, %{"category_id" => category_id, "id" => id}) do
        article = Article
        |> where(hash_id: ^id)
        |> Repo.one!
        |> Repo.preload([:category, :tags, :comments])
        
        if category_id != article.category.hash_id do
            conn 
            |> put_layout(false)
            |> render(HelloPhoenix.ErrorView, "404.html") 
        else
            comments = Comment
            |> where(article_id: ^article.id)
            |> order_by(asc: :inserted_at)
            |> Repo.all

            # 更新文章阅读次数
            Article.changeset(article, %{reading: article.reading + 1}) |> Repo.update!


            changeset = Comment.changeset(%Comment{})

            conn
            |> assign(:article, article)
            |> assign(:comments, comments)
            |> assign(:changeset, changeset)
            |> assign(:category_id, category_id)
            |> render("show.html")
        end
    end
end

web/controllers/user/article_controller.ex
defmodule HelloPhoenix.User.ArticleController do
  use HelloPhoenix.Web, :controller

  alias HelloPhoenix.{ArticleTag, Article, Category, Tag, Comment}

  def index(conn, _params) do
    articles = Article
    |> order_by(desc: :id)
    |> Repo.all
    |> Repo.preload(:category)

    render(conn, "index.html", articles: articles)
  end

  def new(conn, _params) do
    categorys = Repo.all(Category)
    tags = Repo.all(Tag)

    changeset = Article.changeset(%Article{})

    conn
    |> assign(:tags, tags)
    |> assign(:exist_tags, [])
    |> assign(:categorys, categorys)
    |> assign(:changeset, changeset)
    |> render("new.html")
  end

  def create(conn, %{"article" => article_params, "tags" => tag_ids}) do
    changeset = Article.create_changeset(%Article{}, article_params)

    case Repo.insert(changeset) do
      {:ok, article} ->
        article 
        |> Repo.preload(:tags) 
        |> Ecto.Changeset.change()
        |> Ecto.Changeset.put_assoc(:tags, Enum.map(tag_ids, fn id -> Repo.get(Tag, id) end)) 
        |> Repo.update!

        conn
        |> put_flash(:info, "文章创建成功。")
        |> redirect(to: user_article_path(conn, :index))
      {:error, changeset} ->
        conn
        |> assign(:exist_tags, [])
        |> assign(:tags, Repo.all(Tag))
        |> assign(:categorys, Repo.all(Category))
        |> assign(:changeset, changeset)
        |> render("new.html")
    end
  end

  def create(conn, %{"article" => article_params}) do
    changeset = Article.create_changeset(%Article{}, article_params)

    case Repo.insert(changeset) do
      {:ok, _article} ->

        conn
        |> put_flash(:info, "文章创建成功。")
        |> redirect(to: user_article_path(conn, :index))
      {:error, changeset} ->
        conn
        |> assign(:exist_tags, [])
        |> assign(:tags, Repo.all(Tag))
        |> assign(:categorys, Repo.all(Category))
        |> assign(:changeset, changeset)
        |> render("new.html")
    end
   end


  def show(conn, %{"id" => id}) do
    #article = Repo.get!(Article, id)
    #render(conn, "show.html", article: article)
    article = Article
    |> Repo.get!(id)
    |> Repo.preload([:category, :tags, :comments])
    
    comments = Comment
    |> where(article_id: ^article.id)
    |> order_by(asc: :inserted_at)
    |> Repo.all
    changeset = Comment.changeset(%Comment{})
    conn
    |> assign(:article, article)
    |> assign(:comments, comments)
    |> assign(:changeset, changeset)
    |> assign(:category_id, article.category.id)
    |> render("show.html")
  end

  def edit(conn, %{"id" => id}) do
    article = Repo.get!(Article, id) |> Repo.preload(:tags)
    exist_tags = article.tags
    tags = Repo.all(Tag)
    categorys = Repo.all(Category)
    changeset = Article.changeset(article)

    conn
    |> assign(:tags, tags)
    |> assign(:exist_tags, exist_tags)
    |> assign(:article, article)
    |> assign(:changeset, changeset)
    |> assign(:categorys, categorys)
    |> render("edit.html")
  end

  def update(conn, %{"id" => id, "article" => article_params, "tags" => tag_ids}) do
    article = Repo.get!(Article, id)
    changeset = Article.changeset(article, article_params)

    case Repo.update(changeset) do
      {:ok, article} ->
        from(p in ArticleTag, where: p.article_id == ^id) |> Repo.delete_all  # 删除之前所有关联

        article                                                           # 重新插入所有关联
        |> Repo.preload(:tags) 
        |> Ecto.Changeset.change()
        |> Ecto.Changeset.put_assoc(:tags, Enum.map(tag_ids, fn id -> Repo.get(Tag, id) end)) 
        |> Repo.update!

        conn
        |> put_flash(:info, "文章更新成功。")
        |> redirect(to: user_article_path(conn, :show, article))
      {:error, changeset} ->
        conn
        |> assign(:exist_tags, [])
        |> assign(:article, article)
        |> assign(:tags, Repo.all(Tag))
        |> assign(:changeset, changeset)
        |> assign(:categorys, Repo.all(Category))
        |> render("edit.html")
    end
  end

  def update(conn, %{"id" => id, "article" => article_params}) do
    article = Repo.get!(Article, id)
    changeset = Article.changeset(article, article_params)

    case Repo.update(changeset) do
      {:ok, article} ->
        from(p in ArticleTag, where: p.article_id == ^id) |> Repo.delete_all  # 删除之前所有关联

        conn
        |> put_flash(:info, "文章更新成功。")
        |> redirect(to: user_article_path(conn, :show, article))
      {:error, changeset} ->
        conn
        |> assign(:exist_tags, [])
        |> assign(:article, article)
        |> assign(:tags, Repo.all(Tag))
        |> assign(:changeset, changeset)
        |> assign(:categorys, Repo.all(Category))
        |> render("edit.html")
    end
   end


  def delete(conn, %{"id" => id}) do
    article = Repo.get!(Article, id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(article)

    conn
    |> put_flash(:info, "文章删除成功。")
    |> redirect(to: user_article_path(conn, :index))
  end
end

web/views/article_view.ex
defmodule HelloPhoenix.ArticleView do
  use HelloPhoenix.Web, :view

  def markdown(body) do
    body
    |> Earmark.to_html
    |> raw
  end
end

web/views/user/article_view.ex
defmodule HelloPhoenix.User.ArticleView do
  use HelloPhoenix.Web, :view

  def category_name(article) do
    article.category.name
  end

  def markdown(body) do
    body
    |> Earmark.to_html
    |> raw
  end
end

web/templates/article/index.html.eex
范畴:
<ul>
<%= for category <- @categorys do %>
    <li><%= category.name %> </li>
<% end %>
</ul>
<br><br>
<%= for article <- @category.articles do %>
    标题: <%= article.title %>
    内容: <%= article.body %>
    <%= link "Show", to: category_article_path(@conn, :show, @category_id, article), class: "btn btn-default btn-xs" %>
    <br>
<% end %>

web/templates/article/show.html.eex
<div class="container">
    <div id="post-detail-wrap" class="row">
        <div class="col-md-offset-1 col-md-10 phone-no-padding">
            <div class="post-detail">
                <div class="center-block">
                    <div class="post-detail-title"><%= @article.title %></div>
                    <div class="post-meta">
                        <span class="post-time">
                            <i class="fa fa-calendar-o"></i>
                            <time datetime="<%= @article.inserted_at %>">
                                <%= @article.inserted_at %>
                            </time>
                        </span>
                        <span class="post-category">
                            &nbsp;|&nbsp;
                            <i class="fa fa-folder-o"></i>
                            <a href="<%= category_path(@conn, :show, @article.category.hash_id)%>">
                                <%= @article.category.name %>
                            </a>
                        </span>
                        <span class="post-comments-count">
                            &nbsp;|&nbsp;
                            <i class="fa fa-comments-o fa-fw" aria-hidden="true"></i>
                            <span><%= Enum.count @comments %></span>
                        </span>
                        <span>
                            &nbsp;|&nbsp;
                            <i class="fa fa-eye"></i>
                            <span><%= @article.reading %></span>
                        </span>
                    </div>
                </div>
                <br>
                <div class="post-detail-content">
                    <%= markdown @article.body %>
                </div>
                <div class="tag-list">
                    <i class="fa fa-tags"></i>
                    <%= for tag <- @article.tags do %>
                        <a class="tag" href="<%= tag_path(@conn, :show, tag.name) %>"><%= tag.name %></a>
                    <% end %>
                </div>
                <div class="alone-divider"></div>
                <div class="creative-commons">
                    <i class="fa fa-fw fa-creative-commons"></i>自由转载-非商用-非衍生-保持署名（<a
                       href="https://creativecommons.org/licenses/by-nc-nd/3.0/deed.zh">创意共享3.0许可证</a>）
                </div>
            </div>
        </div>
    </div>

    <div class="row mt-30">
        <div id="comment-wrap" class="col-md-offset-1 col-md-10">
            <div class="comment">
                <div class="comment-header">
                    <h6 id="comments_count"><i class="fa fa-comments fa-fw"></i>评论</h6>
                </div>
                <div class="comment-body">
                <%= if @comments == [] do %>
                    <p class="meta-item center-block">暂无评论~~</p>
                <% end %>
                <%= for comment <- @comments do %>
                    <div class="comment-wrap">
                        <div class="pull-left">
                            <a name="comment1" href="#<%= comment.name %>">
                                <img width="40px" height="40px" class="img-circle" src="https://cdn.v2ex.co/avatar/eee9/bf07/136499_large.png?m=1442026544">
                            </a>
                        </div>
                        <div class="comment-info">
                            <div class="comment-head">
                                <span class="name">
                                    <a href="#<%= comment.name %>"><%= comment.name %></a>
                                </span>
                                <span class="comment-operation pull-right">
                                    <a href="javascript:void (0);" onclick="replySomeone('<%= comment.name %>')"><i class="fa fa-reply fa-fw"></i></a>
                                </span>
                            </div>
                            <div class="comment-time">
                                <span><%= comment.inserted_at %></span>
                            </div>
                            <div class="markdown-content">
                                <p><%= comment.body %></p>
                            </div>
                        </div>
                    </div>
                <% end %>
                </div>
                <%= form_for @changeset, category_article_comment_path(@conn, :create, @category_id, @article.hash_id), fn f -> %>
                  <input type="hidden" name="category_id" value="<%= @category_id %>" />
                  <div class="form-group">
                    <%= label f, :username, class: "control-label" %>
                    <%= text_input f, :name, class: "form-control", placeholder: "昵称", id: "username" %>
                  </div>

                  <div class="form-group">
                    <%= label f, :body, class: "control-label" %>
                    <%= textarea f, :body, class: "form-control", placeholder: "至少输入5个字符",  id: "comment-content",  rows: "5", style: "resize: none; overflow: hidden; word-wrap: break-word; height: 174px;"%>
                    <span class="help-block required">
                        <strong id="comment_error_msg"></strong>
                    </span>
                  </div>
                  <div class="form-group">
                    <input type="submit" id="comment-submit" class="btn btn-primary" value="回复"/>
                   </div>

                <% end %>

                </div>
            </div>                
        </div>
    </div>
</div>