web/router.ex
defmodule HelloPhoenix.Router do
  use HelloPhoenix.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

#  pipeline :browser_no_csrf do
#    plug :accepts, ["html"]
#    plug :fetch_session
#    plug :fetch_flash
#    plug :put_secure_browser_headers
#  end

  pipeline :session do
    plug HelloPhoenix.Plugs.Session
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/users", HelloPhoenix, as: :user do
    pipe_through [:browser, :session]

    get "/password/reset", UserController, :edit
    put  "/password/reset", UserController, :update

    get "/", SessionController, :home
    get "/home", SessionController, :home

    get "/settings/profile", User.ProfileController, :show
    get "/upload_avatar", User.UploadController, :new_avatar
    post "/upload_avatar", User.UploadController, :update_avatar
    resources "/categorys", User.CategoryController
    resources "/articles", User.ArticleController
    resources "/comments", User.CommentController
    resources "/tags", User.TagController
    resources "/links", User.LinkController
  end

  scope "/", HelloPhoenix do
    pipe_through :browser # Use the default browser stack

    get "/achieve", AchieveController, :index
    get "/projects", ProjectController, :index
    get "/search", SearchController, :index
    get "/about", AboutController, :index

    get "/users/index", SessionController, :index
    get "/users/login", SessionController, :new
    get "/users/logout", SessionController, :delete
    post "/users/login", SessionController, :create
    get "/users/register", UserController, :new
    post "/users/register", UserController, :create
    resources "/tags", TagController, only: [:show]
    resources "/categorys", CategoryController do
        resources "/articles", ArticleController do
            resources "/comments", CommentController, only: [:create]
        end
    end
    get "/", CategoryController, :index
  end

#  scope "/", HelloPhoenix do
#    pipe_through :browser_no_csrf # Use the default browser stack
#  end
# scope "/admin", HelloPhoenix.Admin, as: :admin do
#   pipe_through :browser
#    
#    resources "/reviews", ReviewController
#    resources "/users", UserController
#k  end

  # Other scopes may use custom stacks.
  # scope "/api", HelloPhoenix do
  #   pipe_through :api
  # end
end

web/controllers/search_controller.ex
defmodule HelloPhoenix.SearchController do
  use HelloPhoenix.Web, :controller

  alias HelloPhoenix.{Category, Tag, Article, Link}

  defp common(conn) do
    categorys = Category
    |> Repo.all
    |> Repo.preload(:articles)
  
    tags = Tag
    |> Repo.all
    |> Repo.preload(:articles)
  
    hot_articles = Article
    |> where(block: false)
    |> order_by(desc: :reading)
    |> limit(10)
    |> Repo.all
    |> Repo.preload(:category)

    links = ConCache.get_or_store(:hello_phoenix, "links", fn() -> 
      Link
      |> Repo.all
    end)
  
    conn
    |> assign(:hot_articles, hot_articles)
    |> assign(:categorys, categorys)
    |> assign(:tags, tags)
    |> assign(:links, links)
  end

  def index(conn, params) do
    conn = common(conn)
    pagination = case Map.fetch(params, "q") do
      {:ok, query} ->
        query = "%" <> query <> "%"
        articles = from(a in Article, where: like(a.body, ^query)) 
                   |> where(block: false)
                   |> order_by(desc: :inserted_at)
                   |> preload([:comments, :category, :tags]) 
                   |> Repo.paginate(params)
        if articles.entries == [] do
            []
        else
            articles
        end
      {:error} ->
        []
    end
    conn
    |> assign(:pagination, pagination)
    |> render(:index)
  end
end

web/views/search_view.ex
defmodule HelloPhoenix.SearchView do
  use HelloPhoenix.Web, :view
end

web/templates/search/index.html.eex
<div id="content-wrap">
    <div class="container">
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <%= render HelloPhoenix.ShareView, "article_body.html", pagination: @pagination, conn: @conn %>
                <%= if @pagination != [] do %> 
                    <%= pagination_links @conn, @pagination, path: &search_path/3, action: :index, q: Map.get(@conn.params, "q") %>
                <%= else %>
                    <div class="widget widget-default">
                        <div class="widget-header">
                            <h3>搜索 "<%= Map.get(@conn.params, "q") %>"</h3>
                        </div>
                        <div class="widget-body">
                            <h4>什么也没搜到...</h4>
                        </div>
                    </div>
                <% end %>
            </div>
            <div class="col-md-4">
                <div class="slide">
                    <!-- 个人信息-->
                    <%= render HelloPhoenix.ShareView, "user_info.html" %>
                    <%= render HelloPhoenix.ShareView, "hot_articles.html", hot_articles: @hot_articles, conn: @conn %>
                    <%= render HelloPhoenix.ShareView, "category.html", categorys: @categorys, conn: @conn %>
                    <%= render HelloPhoenix.ShareView, "tag.html", tags: @tags, conn: @conn %>
                    <!-- 友情链接-->
                    <%= render HelloPhoenix.ShareView, "friend_ship.html", links: @links %>
                </div>
            </div>
        </div>
    </div>
</div>